Repository Goader/planty, pull requests merged in 2022-06, with the labels that each got.

#35 [PVD-128] Plant get endpoint
  backend/planty/dashboard/models.py
  backend/planty/dashboard/urls.py
  backend/planty/dashboard/views.py
Labels: enhancement

#36 [PVD-147] Image cropping to a square
  backend/planty/dashboard/serializers.py
  backend/planty/dashboard/utils.py
  backend/planty/dashboard/views.py
Labels: enhancement

#28 [PVD-116] Popular instructions endpoint
  .gitignore
  backend/planty/dashboard/models.py
  backend/planty/dashboard/serializers.py
  backend/planty/dashboard/urls.py
  backend/planty/dashboard/views.py
Labels: enhancement

#41 [PVD-117] Instructions view
  backend/planty/dashboard/admin.py
  backend/planty/dashboard/serializers.py
  backend/planty/dashboard/views.py
  frontend/src/api/instructions.ts
  frontend/src/components/card/InstructionCard.tsx
  frontend/src/components/card/PlantCard.tsx
  frontend/src/components/instruction/AddInstructionModal.tsx
  frontend/src/components/instruction/EditInstructionModal.tsx
  frontend/src/components/instruction/InstructionForm.tsx
  frontend/src/components/instruction/InstructionModal.tsx
  frontend/src/model/instructions.ts
  frontend/src/views/InstructionsView.tsx
  frontend/src/views/MainView.tsx
Labels: enhancement

#44 [PVD-151] add max value for watering/fertilizing, add insolation valiadator and fix missing plant_photo bug
  backend/planty/dashboard/serializers.py
  backend/planty/dashboard/validators.py
  backend/planty/dashboard/views.py
Labels: bug, good first issue

#42 [PVD-151] remove "elo" console log :D
  frontend/src/components/AccountSettingsForm.tsx
Labels: good first issue

#43 [PVD-151] Email added to registration
  backend/planty/users/serializers.py
  frontend/src/api/auth/AuthContext.tsx
  frontend/src/api/auth/auth.ts
  frontend/src/views/RegisterView.tsx
Labels: enhancement

#47 [PVD-151] Settings buttons
  frontend/src/components/AccountSettingsForm.tsx
  frontend/src/components/plant/AddPlantModal.tsx
  frontend/src/components/plant/PlantForm.tsx
  frontend/src/views/AccountSettingsView.tsx
  frontend/src/views/GardenView.tsx
Labels: bug
