Repository Goader/planty, pull requests merged in 2022-05, with the labels that each got.

#16 improve yarn installation instructions
  readme.md
Labels: documentation

#18 Settings app with user settings
  backend/planty/planty/settings.py
  backend/planty/planty/urls.py
  backend/planty/settings/__init__.py
  backend/planty/settings/admin.py
  backend/planty/settings/apps.py
  backend/planty/settings/models.py
  backend/planty/settings/serializers.py
  backend/planty/settings/tests.py
  backend/planty/settings/urls.py
  backend/planty/settings/views.py
Labels: enhancement

#22 [PVD-135] Custom Event Endpoint
  backend/planty/dashboard/models.py
  backend/planty/dashboard/serializers.py
  backend/planty/dashboard/urls.py
  backend/planty/dashboard/views.py
Labels: enhancement

#23 [PVD-141] Plant image
  backend/.gitignore
  backend/planty/dashboard/migrations/__init__.py
  backend/planty/dashboard/models.py
  backend/planty/dashboard/serializers.py
  backend/planty/dashboard/views.py
  backend/planty/planty/settings.py
  backend/planty/planty/urls.py
  backend/requirements.txt
  frontend/src/api/plants.ts
  frontend/src/components/card/PlantCard.tsx
  frontend/src/model/plants.ts
  frontend/src/views/AddPlantFormView.tsx
Labels: enhancement

#21 [PVD-134] Events History
  backend/planty/dashboard/models.py
  backend/planty/dashboard/serializers.py
  backend/planty/dashboard/views.py
Labels: enhancement

#30 [PVD-72] Notifications settings
  frontend/package.json
  frontend/src/App.test.tsx
  frontend/src/App.tsx
  frontend/src/api/settings.ts
  frontend/src/components/AccountSettingsForm.tsx
  frontend/src/components/navbar/PlantyNavbar.tsx
  frontend/src/model/settings.ts
  frontend/src/views/AccountSettingsView.tsx
  frontend/yarn.lock
Labels: enhancement

#7 [PVD-77] Notifications server for scheduling email sendings
  .gitignore
  backend/.gitignore
  backend/docker-compose.yml
  backend/notifications/.env
  backend/notifications/Dockerfile
  backend/notifications/app.py
  backend/notifications/models.py
  backend/notifications/notifier.py
  backend/notifications/readme.md
  backend/notifications/requirements.txt
  backend/notifications/scheduler.py
  backend/notifications/trigger.py
  backend/planty/dashboard/migrations/0001_initial.py
  backend/planty/dashboard/notifier.py
  backend/planty/dashboard/views.py
  backend/planty/planty/settings.py
  backend/planty/requirements.txt
  backend/planty/settings/migrations/0001_initial.py
  backend/planty/settings/migrations/__init__.py
Labels: enhancement

#33 [PVD-143] Consistent events
  backend/planty/dashboard/migrations/0001_initial.py
  backend/planty/dashboard/models.py
  backend/planty/dashboard/serializers.py
  backend/planty/dashboard/views.py
  backend/planty/settings/migrations/0001_initial.py
Labels: refactoring
